name: mlde_Josh_L_2.9
channels:
  - conda-forge
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.3=hb03c661_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - cftime=1.6.5=py310hf779ad0_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - codetiming=1.4.0=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h24cb091_1
  - docker-pycreds=0.4.0=py_0
  - double-conversion=3.4.0=hecca717_0
  - einops=0.8.1=pyhd8ed1ab_0
  - eval_type_backport=0.3.1=pyha770c72_0
  - ffmpeg=8.0.1=gpl_hf567e27_909
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - glslang=16.1.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h6083320_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h1b119a7_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - imath=3.2.2=hde8ca8f_0
  - intel-gmmlib=22.9.0=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - jasper=4.2.8=he3c4edf_0
  - jsmin=3.0.1=pyhd8ed1ab_1
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.27.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=4_h0358290_openblas
  - libclang-cpp21.1=21.1.8=default_h99862b1_1
  - libclang13=21.1.8=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-ng=15.2.0=h69a702a_15
  - libgfortran=15.2.0=h69a702a_15
  - libgfortran5=15.2.0=h68bc16d_15
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_15
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=ha09017c_8
  - liblapack=3.11.0=4_h47877c9_openblas
  - liblapacke=3.11.0=4_h6ae95b6_openblas
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopencv=4.12.0=qt6_py310h10c537f_612
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2025.4.1=hb56ce9e_0
  - libopenvino-auto-batch-plugin=2025.4.1=hd85de46_0
  - libopenvino-auto-plugin=2025.4.1=hd85de46_0
  - libopenvino-hetero-plugin=2025.4.1=hd41364c_0
  - libopenvino-intel-cpu-plugin=2025.4.1=hb56ce9e_0
  - libopenvino-intel-gpu-plugin=2025.4.1=hb56ce9e_0
  - libopenvino-intel-npu-plugin=2025.4.1=hb56ce9e_0
  - libopenvino-ir-frontend=2025.4.1=hd41364c_0
  - libopenvino-onnx-frontend=2025.4.1=h1862bb8_0
  - libopenvino-paddle-frontend=2025.4.1=h1862bb8_0
  - libopenvino-pytorch-frontend=2025.4.1=hecca717_0
  - libopenvino-tensorflow-frontend=2025.4.1=h0767aad_0
  - libopenvino-tensorflow-lite-frontend=2025.4.1=hecca717_0
  - libopus=1.6.1=h280c20c_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.54=h421ea60_0
  - libpq=18.1=hb80d175_3
  - libprotobuf=6.31.1=h49aed37_4
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc7d488a_2
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.3=h6569c3e_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.13=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=h5347b49_1
  - libva=2.23.0=he1eb515_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.15.2=hecca717_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxslt=1.1.43=h711ed8c_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - matplotlib-base=3.10.8=py310hfde16b3_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mpg123=1.32.9=hc50e24c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=qt6_py310hec850f8_612
  - openexr=3.4.4=h40f6f1d_1
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.26.0=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=hadf4263_0
  - pcre2=10.47=haa7fec5_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - proj=9.6.2=h18fbb6c_2
  - protobuf=6.31.1=py310ha36e12e_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - py-opencv=4.12.0=qt6_py310h89973df_612
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310hd8f68c5_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyproj=3.7.1=py310h71d0299_1
  - pyside6=6.10.1=py310h2007e60_0
  - pysocks=1.7.1=pyha55dd90_7
  - pysteps=1.18.1=py310hf779ad0_0
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyyaml=6.0.3=py310h3406613_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.1=hb82b983_4
  - rav1e=0.7.1=h8fae777_3
  - readline=8.2=h8c095d6_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.2.0=pyhcf101f3_0
  - rpds-py=0.30.0=py310hd8f68c5_0
  - scipy=1.15.2=py310h1d65ade_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.30=h3b84278_0
  - sentry-sdk=2.50.0=pyhd8ed1ab_0
  - setproctitle=1.3.7=py310h139afa4_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.5=h3e344bc_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.51.1=hbc0de68_0
  - svt-av1=3.1.2=hecca717_0
  - tbb=2022.3.0=hb700be7_2
  - tensorboardx=2.6.2.2=pyhd8ed1ab_1
  - tk=8.6.13=noxft_ha0e22de_103
  - typer=0.20.0=pyhefaf540_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typer-slim-standard=0.20.0=h4daf872_1
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - wandb=0.23.1=py310h4a20303_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.47=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - git+https://github.com/xarray-contrib/xskillscore.git
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asciitree==0.3.3
      - asttokens==3.0.1
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - cartopy==0.25.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dotenv==0.9.9
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.61.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - lightning-utilities==0.15.2
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - ml-collections==1.1.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netcdf4==1.7.3
      - networkx==3.3
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - numcodecs==0.13.1
      - numpy==2.1.2
      - nvidia-cublas==13.0.0.19
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufile==1.15.0.42
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - overrides==7.7.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pyparsing==3.2.5
      - pyshp==3.0.3
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - pytorch-lightning==2.6.0
      - pytorch-msssim==1.0.0
      - pytz==2025.2
      - pyzmq==27.1.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - send2trash==1.8.3
      - shapely==2.1.2
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.14.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.3.0
      - torch==2.9.1+cu130
      - torchinfo==1.8.0
      - torchmetrics==1.8.2
      - torchvision==0.24.1+cu130
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.5.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - xarray==2025.6.1
      - yarl==1.22.0
      - zarr==2.18.3